export const allUserDetailsJson = [
  {
    sl: 1,
    name: "মোঃ রোমান উদ্দীন",
    username: "roman",
    father: "মোঃ আবুল কাশেম",
    mother: "রুবি আক্তার",
    village: "ফকিরাচাঁন",
    dob: "১৫/১০/১৯৯৯",
    mobile: "00971544672832",
    bank_account: "0852050023894 (One bank)",
    nid: "",
    workplace: "দুবাই",
    nominee: "রুবি আক্তার",
    profile_image: "src/profile_pic/1.jpeg"
  },
  {
    sl: 2,
    name: "মুহাম্মদ হারুন",
    username: "harun",
    father: "মুহাম্মদ লোকমান",
    mother: "শাহানারা বেগম",
    village: "পূর্ব ভূজপুর মিরেরখীল",
    dob: "০৮/০৮/২০০০",
    mobile: "+৯৭১৫৫৭৮৮১৩২২",
    bank_account: "",
    nid: "",
    workplace: "দুবাই",
    nominee: "মুহাম্মদ ইমরুল হাসান",
    profile_image: "src/profile_pic/2.jpeg"
  },
  {
    sl: 3,
    name: "মোহাম্মদ রিজোয়ান",
    username: "rizowan",
    father: "মৃত বদিউল আলম",
    mother: "আয়েশা খাতুন",
    village: "পূর্ব ভূজপুর (দাইয়াপাড়া-৭নং ওয়ার্ড)",
    dob: "১১/০২/২০০০",
    mobile: "০১৬০৯২৬৫২২৩ (নগদ, WhatsApp)",
    bank_account: "0010192534201 (CBBL)",
    nid: "5564760162",
    workplace: "কক্সবাজার",
    nominee: "সিয়াম (ছেলে)",
    profile_image: "src/profile_pic/3.jpeg"
  },
  {
    sl: 4,
    name: "মুহাম্মদ রাহাত হোসেন",
    username: "rahat",
    father: "নুরুল ইসলাম",
    mother: "রেশমা আক্তার",
    village: "পূর্ব ভূজপুর (৮নং ওয়ার্ড)",
    dob: "২৫/০৭/২০০০",
    mobile: "০১৮৩৮৭০১৮৩৬ (বিকাশ, WhatsApp)",
    bank_account: "7017512780569 (DBBL)",
    nid: "7364656228",
    workplace: "প্রবাসি",
    nominee: "রিয়াদ (ভাই)",
    profile_image: "src/profile_pic/4.jpeg"
  },
  {
    sl: 5,
    name: "মো: ইয়াছিন",
    username: "yasin",
    father: "মো: শফি উল আলম",
    mother: "মোছা: ফরিদা বেগম",
    village: "আজিম পুর (৯নং ওয়ার্ড)",
    dob: "১০/০২/১৯৯৯",
    mobile: "0096891610097",
    bank_account: "",
    nid: "",
    workplace: "ওমান প্রবাসী",
    nominee: "আজওয়াদ",
    profile_image: "src/profile_pic/5.jpeg"
  },
  {
    sl: 6,
    name: "মো: আনোয়ার হোসেন",
    username: "anowar",
    father: "মৃত মো: নুরুল বশর",
    mother: "খতিজা বেগম",
    village: "পূর্ব ভুজপুর (৮নং ওয়ার্ড)",
    dob: "০২/০১/২০০২",
    mobile: "0096878122023",
    bank_account: "",
    nid: "",
    workplace: "ওমান প্রবাসী",
    nominee: "মো: সরওয়ার",
    profile_image: "src/profile_pic/6.jpeg"
  },
  {
    sl: 7,
    name: "সৈয়দ মোহাম্মদ তারেক",
    username: "tarek",
    father: "মৃত সৈয়দ মোহাম্মদ আবুল হাসেম",
    mother: "হোসনে আরা বেগম",
    village: "আজিমপুর",
    dob: "১০/০৬/২০০০",
    mobile: "77365651",
    bank_account: "",
    nid: "6014599291",
    workplace: "ওমান নেষ্টু হাইপার মার্কেট",
    nominee: "হোসনে আরা বেগম",
    profile_image: "src/profile_pic/7.jpeg"
  },
  {
    sl: 8,
    name: "মো: মোজাম্মেল হোসেন",
    username: "mozammel",
    father: "মো: মোজাহেরুল ইসলাম",
    mother: "পারভীন আক্তার",
    village: "আজিমপুর, চৌধুরী বাড়ী (৯নং ওয়ার্ড)",
    dob: "১৬/১২/২০০০",
    mobile: "00968-78649868 (ওমান)",
    bank_account: "",
    nid: "",
    workplace: "ওমান প্রবাসী",
    nominee: "মো: সাফওয়ান চৌধুরী",
    profile_image: "src/profile_pic/8.jpeg"
  },
  {
    sl: 9,
    name: "মিজানুর রহমান",
    username: "mizan",
    father: "বাদশা মিয়া",
    mother: "নুর নাহার বেগম",
    village: "পূর্ব ভুজপুর তালুকদার পাড়া",
    dob: "১৩/০৬/১৯৯৯",
    mobile: "01867131052",
    bank_account: "2506212016673 (প্রাইম ব্যাংক ভূজপুর শাখা)",
    nid: "5555048197",
    workplace: "ভুজপুর কাজিরহাট",
    nominee: "বাদশা মিয়া",
    profile_image: "src/profile_pic/9.jpeg"
  },
  {
    sl: 10,
    name: "নাজিম উদ্দিন রাসেল",
    username: "rasel",
    father: "মোহাম্মদ আলম",
    mother: "শাহিনা বেগম",
    village: "আজিমপুর আদর্শ গ্রাম",
    dob: "১২/১০/১৯৯৮",
    mobile: "+96891894246",
    bank_account: "",
    nid: "",
    workplace: "মাসকাট, ওমান",
    nominee: "নাফিজুর রহমান (ছেলে)",
    profile_image: "src/profile_pic/10.jpeg"
  },
  {
    sl: 11,
    name: "রবিউল হাসান",
    username: "robiul",
    father: "মৃত মোহাম্মদ ইউনুস",
    mother: "মৃত পারভিন আক্তার",
    village: "আজিমপুর",
    dob: "২৭/১২/১৯৯৬",
    mobile: "01863604906",
    bank_account: "",
    nid: "8255040068",
    workplace: "চট্টগ্রাম",
    nominee: "হুমাইরা (স্ত্রী)",
    profile_image: "src/profile_pic/11.jpeg"
  },
  {
    sl: 12,
    name: "মো: মিনহাজ উদ্দিন চৌধুরী",
    username: "minhaj",
    father: "মো: হারুন চৌধুরী",
    mother: "বিবি ফাতেমা",
    village: "আজিমপুর",
    dob: "১৫/০১/২০০১",
    mobile: "+971508452433",
    bank_account: "",
    nid: "2864601410",
    workplace: "আরব আমিরাত",
    nominee: "মো: বোরহান উদ্দিন চৌধুরী (ভাই)",
    profile_image: "src/profile_pic/12.jpeg"
  },
  {
    sl: 13,
    name: "মোহাম্মদ মোজাম্মেল হোসেন",
    username: "mozammel2",
    father: "মো: আবুল বশর",
    mother: "মোছাম্মৎ রেজিয়া বেগম",
    village: "পূর্ব ভূজপুর মাইজপাড়া নতুন বাড়ি",
    dob: "২৬/০৩/১৯৯৯",
    mobile: "01878770226",
    bank_account: "2506212018067",
    nid: "5105025349",
    workplace: "ভুজপুর",
    nominee: "মো: তৈয়ব",
    profile_image: "src/profile_pic/13.jpeg"
  },
  {
    sl: 14,
    name: "মো: সজীব উদ্দীন",
    username: "sojib",
    father: "তাজুল ইসলাম",
    mother: "সুফিয়া বেগম",
    village: "ফকিরাচান",
    dob: "১৫/০১/১৯৯৮",
    mobile: "+400748410799",
    bank_account: "",
    nid: "",
    workplace: "রোমানিয়া",
    nominee: "সুফিয়া বেগম (মা)",
    profile_image: "src/profile_pic/14.jpeg"
  },
  {
    sl: 15,
    name: "প্রসেন ত্রিপুরা",
    username: "proshen",
    father: "কোকিলা কুমার ত্রিপুরা",
    mother: "শান্তি বালা ত্রিপুরা",
    village: "হারুয়ালছড়ি (ফুলচাঁন পাড়া ০৬ নং ওয়ার্ড)",
    dob: "১৪/১০/১৯৯৯",
    mobile: "01612113158 (বিকাশ, WhatsApp)",
    bank_account: "",
    nid: "19991513342106399",
    workplace: "চট্টগ্রাম, অক্সিজেন পাবলিক",
    nominee: "শান্তি বালা ত্রিপুরা (মা)",
    profile_image: "src/profile_pic/15.jpeg"
  },
  {
    sl: 16,
    name: "টিটু মিয়া",
    username: "titu",
    father: "নুরুল আলম",
    mother: "মৃত রশিদা বেগম",
    village: "আজিমপুর",
    dob: "০৫/০১/২০০১",
    mobile: "01869486675",
    bank_account: "",
    nid: "3314585385",
    workplace: "ভুজপুর কাজির হাট",
    nominee: "",
    profile_image: "src/profile_pic/16.jpeg"
  },
  {
    sl: 17,
    name: "সৈয়দ আব্বাস আলাহী",
    username: "abbas",
    father: "Sayed Ashak Alahee",
    mother: "Sayeda Momena Begum",
    village: "West Bhujpur",
    dob: "১৭/১২/২০০০",
    mobile: "+971547564960, 01820054666",
    bank_account: "",
    nid: "",
    workplace: "United Arab Emirates",
    nominee: "Sayed Nur Alahee",
    profile_image: "src/profile_pic/17.jpeg"
  },
  {
    sl: 18,
    name: "মো: শহিদুল্লাহ",
    username: "shahid",
    father: "মোহাম্মদ হোসেন",
    mother: "ছবুরা খাতুন",
    village: "আজিমপুর",
    dob: "১৫/০৪/১৯৯৯",
    mobile: "01831100911",
    bank_account: "",
    nid: "2864605577",
    workplace: "ভুজপুর কাজির হাট",
    nominee: "মো: হামিদুল্লাহ",
    profile_image: "src/profile_pic/18.jpeg"
  },
  {
    sl: 19,
    name: "মো: রাহাদ আহমেদ চৌধুরী",
    username: "rahad",
    father: "মো: খায়রুল আমিন চৌধুরী",
    mother: "রুজি আমিন চৌধুরী",
    village: "পূর্ব ভূজপুর, চৌধুরী পাড়া (৯নং ওয়ার্ড)",
    dob: "১০/০১/২০০১",
    mobile: "01868761580 (WhatsApp, বিকাশ)",
    bank_account: "2506215019427 (Prime Bank)",
    nid: "2864604778",
    workplace: "ব্যবসা (চৌধুরী পাড়া)",
    nominee: "রুজি আমিন চৌধুরী (মা)",
    profile_image: "src/profile_pic/19.jpeg"
  },
  {
    sl: 20,
    name: "মো: গালিব চৌধুরী",
    username: "galib",
    father: "মহিম উদ্দিন চৌধুরী",
    mother: "সুকিলা আকতার",
    village: "আজিমপুর",
    dob: "২৯/০১/২০০১",
    mobile: "01839731101",
    bank_account: "2139213024473",
    nid: "",
    workplace: "কাজিরহাট",
    nominee: "সুকিলা আকতার",
    profile_image: "src/profile_pic/20.jpeg"
  },
  {
    sl: 21,
    name: "ইয়াছার মোস্তাফা সাজিদ",
    username: "sajid",
    father: "নাসিম উদ্দিন",
    mother: "কানিজ মোস্তফা",
    village: "আজিমপুর, ৯ নং ওয়ার্ড",
    dob: "২৯/০৯/২০০১",
    mobile: "০১৮৩৭৮১৬৮৪০",
    bank_account: "",
    nid: "১০৩৩০৭৮২২৯",
    workplace: "সিলেট",
    nominee: "কানিজ মোস্তফা (মা)",
    profile_image: "src/profile_pic/21.jpeg"
  }
];

  